-- Sample SQL migration file for the Job Application Management System
-- This file shows the SQL that would be generated by Prisma migrate

-- CreateTable Users
CREATE TABLE "users" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable UserProfiles
CREATE TABLE "user_profiles" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "phoneNumber" TEXT,
    "linkedinUrl" TEXT,
    "portfolioUrl" TEXT,
    "githubUrl" TEXT,
    "currentJobTitle" TEXT,
    "currentCompany" TEXT,
    "yearsOfExperience" INTEGER,
    "preferredJobTypes" TEXT,
    "preferredLocations" TEXT,
    "expectedSalaryMin" INTEGER,
    "expectedSalaryMax" INTEGER,
    "salaryCurrency" TEXT NOT NULL DEFAULT 'HKD',
    "noticePeriod" TEXT,
    "professionalSummary" TEXT,
    "skills" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "user_profiles_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable JobApplications
CREATE TABLE "job_applications" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "jobListingId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "appliedDate" DATETIME,
    "applicationMethod" TEXT,
    "contactPerson" TEXT,
    "contactEmail" TEXT,
    "coverLetterContent" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "job_applications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "job_applications_jobListingId_fkey" FOREIGN KEY ("jobListingId") REFERENCES "job_listings" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable ApplicationStatusHistory
CREATE TABLE "application_status_history" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "applicationId" TEXT NOT NULL,
    "fromStatus" TEXT,
    "toStatus" TEXT NOT NULL,
    "changedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "changedBy" TEXT,
    "notes" TEXT,
    CONSTRAINT "application_status_history_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "job_applications" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable Interviews
CREATE TABLE "interviews" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "applicationId" TEXT NOT NULL,
    "interviewType" TEXT NOT NULL,
    "interviewRound" INTEGER NOT NULL DEFAULT 1,
    "scheduledDate" DATETIME NOT NULL,
    "duration" INTEGER,
    "location" TEXT,
    "meetingLink" TEXT,
    "preparationNotes" TEXT,
    "questionsToAsk" TEXT,
    "completed" BOOLEAN NOT NULL DEFAULT false,
    "feedback" TEXT,
    "outcome" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "interviews_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "job_applications" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable Interviewers
CREATE TABLE "interviewers" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "interviewId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "title" TEXT,
    "email" TEXT,
    "linkedinUrl" TEXT,
    "notes" TEXT,
    CONSTRAINT "interviewers_interviewId_fkey" FOREIGN KEY ("interviewId") REFERENCES "interviews" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable ApplicationDocuments
CREATE TABLE "application_documents" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "applicationId" TEXT,
    "documentType" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "description" TEXT,
    "tags" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "application_documents_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "application_documents_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "job_applications" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable ApplicationReminders
CREATE TABLE "application_reminders" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "reminderType" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "dueDate" DATETIME NOT NULL,
    "isCompleted" BOOLEAN NOT NULL DEFAULT false,
    "completedAt" DATETIME,
    "isSnoozed" BOOLEAN NOT NULL DEFAULT false,
    "snoozedUntil" DATETIME,
    "emailNotification" BOOLEAN NOT NULL DEFAULT true,
    "notificationSent" BOOLEAN NOT NULL DEFAULT false,
    "notificationSentAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "application_reminders_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "application_reminders_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "job_applications" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "user_profiles_userId_key" ON "user_profiles"("userId");
CREATE UNIQUE INDEX "job_applications_userId_jobListingId_key" ON "job_applications"("userId", "jobListingId");
CREATE INDEX "job_applications_userId_idx" ON "job_applications"("userId");
CREATE INDEX "job_applications_jobListingId_idx" ON "job_applications"("jobListingId");
CREATE INDEX "job_applications_status_idx" ON "job_applications"("status");
CREATE INDEX "application_status_history_applicationId_idx" ON "application_status_history"("applicationId");
CREATE INDEX "interviews_applicationId_idx" ON "interviews"("applicationId");
CREATE INDEX "interviews_scheduledDate_idx" ON "interviews"("scheduledDate");
CREATE INDEX "application_documents_userId_idx" ON "application_documents"("userId");
CREATE INDEX "application_documents_applicationId_idx" ON "application_documents"("applicationId");
CREATE INDEX "application_documents_documentType_idx" ON "application_documents"("documentType");
CREATE INDEX "application_reminders_userId_idx" ON "application_reminders"("userId");
CREATE INDEX "application_reminders_applicationId_idx" ON "application_reminders"("applicationId");
CREATE INDEX "application_reminders_dueDate_idx" ON "application_reminders"("dueDate");

-- Add relation to JobListings
ALTER TABLE "job_listings" ADD COLUMN "applicationCount" INTEGER NOT NULL DEFAULT 0;